package main;

import java.util.Scanner;

/**
 * 
 * @author devinlewis
 *
 *
 *this class calls the constructors and methods of the cube class 
 */

public class CubeDriver {

	public static void main(String[] args) {
		Scanner side = new Scanner(System.in);
		
		
		/**
		 * takes in user input for a number
		 *  and stores in the value side length 
		 */
		System.out.println("enter a number: ");
		double sideLength = side.nextDouble();
		
		/**
		 * constructor method for cube object 
		 */
		cube user = new cube(sideLength);
		
		/**
		 * calculates the surface of the area of the cube generated by 
		 * the user entered number 
		 */
		System.out.println(user.surfaceArea());
		
		/**
		 * calculates the volume of the cube based on the number entered 
		 * by the user
		 */
		System.out.println(user.volume());
		

	}

}
